# Generated by Django 5.0.4 on 2024-06-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VEO', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veoservices',
            name='GaragePN',
            field=models.TextField(null=True),
        ),
    ]
